In [18]:
import pandas as pd

In [69]:
na_val=[' ']
df = pd.read_csv('glassdoor_jobs.csv',na_values=na_val)

In [70]:
df.shape

(956, 15)

In [21]:
df

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
5,5,Data Scientist,$71K-$119K (Glassdoor est.),CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 to 500 employees,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix"
6,6,Data Scientist,$54K-$93K (Glassdoor est.),Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 to 1000 employees,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1
7,7,Data Scientist,$86K-$142K (Glassdoor est.),Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 to 500 employees,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1
8,8,Research Scientist,$38K-$84K (Glassdoor est.),SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+ employees,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1
9,9,Data Scientist,$120K-$160K (Glassdoor est.),isn’t your usual company. Our work is powered ...,4.6,<intent>\n4.6,"New York, NY","New York, NY",51 to 200 employees,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel"
10,10,Data Scientist,$126K-$201K (Glassdoor est.),"At Wish, our Data Science & Engineering team i...",3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 to 1000 employees,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1
11,11,Data Scientist,$64K-$106K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
12,12,Staff Data Scientist - Technology,$106K-$172K (Glassdoor est.),Position Summary...\nDrives the execution of m...,3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+ employees,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon"
13,13,Data Analyst,$46K-$85K (Glassdoor est.),"Are you an experienced Data Analyst, skilled a...",4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1
14,14,Data Scientist,$83K-$144K (Glassdoor est.),Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer"
15,15,Data Engineer I,$102K-$190K (Glassdoor est.),This opportunity is within Audibles Data Engin...,3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 to 5000 employees,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1
16,16,"Scientist I/II, Biology",$67K-$137K (Glassdoor est.),"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 to 200 employees,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene"
17,17,Customer Data Scientist,$118K-$189K (Glassdoor est.),Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 to 500 employees,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
18,18,Data Scientist - Health Data Analytics,$110K-$175K (Glassdoor est.),"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
19,19,Data Scientist,$64K-$111K (Glassdoor est.),"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
20,20,Data Scientist,$81K-$130K (Glassdoor est.),About Our Team\n\nWe understand that the first...,3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack"
21,21,Senior Data Scientist / Machine Learning,$73K-$119K (Glassdoor est.),IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 to 500 employees,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1
22,22,Data Scientist - Quantitative,$86K-$139K (Glassdoor est.),Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 to 1000 employees,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1
23,23,Data Scientist,$63K-$105K (Glassdoor est.),Position Summary\nOur Data Science team is cur...,4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 to 200 employees,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1
24,24,Data Scientist,-1,JOB CATEGORY:\n\nInformation Services\n\nREQUI...,3.9,Mars\n3.9,Oregon,"Mc Lean, VA",10000+ employees,1911,Company - Private,Food & Beverage Manufacturing,Manufacturing,$10+ billion (USD),-1
25,25,Data Scientist,$109K-$177K (Glassdoor est.),Are you passionate about solving challenging p...,4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton"
26,26,Digital Health Data Scientist,$63K-$110K (Glassdoor est.),ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
27,27,Data Scientist,$75K-$124K (Glassdoor est.),As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 to 5000 employees,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1
28,28,Associate Data Analyst,$34K-$61K (Glassdoor est.),"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
29,29,Clinical Data Scientist,$63K-$105K (Glassdoor est.),THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
926,926,Scientist - Analytical Services,$65K-$134K (Glassdoor est.),British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1
927,927,"Head Data Scientist – Image Analytics lead, No...",-1,"06-Feb-2020\n\nJob ID\n279186BR\n{""QuestionNam...",3.8,Novartis\n3.8,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
928,928,"Associate Scientist / Sr. Associate Scientist,...",$59K-$125K (Glassdoor est.),"Who we are\n\n23andMe, the leading consumer ge...",4.0,23andMe\n4.0,"South San Francisco, CA","Sunnyvale, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Ancestry, Verily Life Sciences, Abbott Laborat..."
929,929,Associate Data Analyst- Graduate Development P...,$32K-$59K (Glassdoor est.),Overview\n\n\nNational Interstate is a member ...,3.3,National Interstate\n3.3,"Richfield, OH","Richfield, OH",501 to 1000 employees,1989,Company - Private,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1
930,930,Sr. Data Engineer,$87K-$158K (Glassdoor est.),Join our team of Data Consultants and work on ...,4.5,Moser Consulting\n4.5,"Indianapolis, IN","Indianapolis, IN",51 to 200 employees,1996,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1
931,931,Clinical Data Analyst,$27K-$48K (Glassdoor est.),Job Summary\n\n\nGreenway Health is actively s...,3.0,Greenway Health\n3.0,"Tampa, FL","Tampa, FL",1001 to 5000 employees,1977,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"eClinicalWorks, NextGen Healthcare, athenahealth"
932,932,IT Associate Data Analyst,$39K-$69K (Glassdoor est.),"Monday, November 25, 2019\n\nOur Personal Line...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1
933,933,Business Data Analyst,$36K-$71K (Glassdoor est.),(We are unable to sponsor for this role now or...,3.8,Fareportal\n3.8,"New York, NY","New York, NY",1001 to 5000 employees,2002,Company - Private,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com"
934,934,Senior Insurance Data Scientist,$107K-$173K (Glassdoor est.),"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion\n3.9,"Chicago, IL","Chicago, IL",5001 to 10000 employees,1968,Company - Public,Financial Analytics & Research,Finance,$1 to $2 billion (USD),-1
935,935,Senior Data Science Systems Engineer,$56K-$99K (Glassdoor est.),"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE\n3.2,"Hampton, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC"
936,936,ENVIRONMENTAL ENGINEER/SCIENTIST,Employer Provided Salary:$25-$28 Per Hour,"McPhail Associates, LLC is a geotechnical and ...",3.3,Mcphail Associates\n3.3,"Cambridge, MA","Cambridge, MA",1 to 50 employees,1976,Company - Private,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable,-1
937,937,"Scientist, Product Development",-1,Requisition Number:\nVALA4948\n\nJob Title:\nS...,2.9,Pharmavite\n2.9,"Valencia, CA","West Hills, CA",1001 to 5000 employees,1971,Company - Private,Consumer Products Manufacturing,Manufacturing,$1 to $2 billion (USD),"The Nature's Bounty Co., Schiff Nutrition Inte..."
938,938,Senior Scientist - Regulatory Submissions,$80K-$155K (Glassdoor est.),British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1
939,939,Scientist - Biomarker and Flow Cytometry,$43K-$98K (Glassdoor est.),"Crown Bioscience, a JSR Life Sciences company,...",2.4,Crown Bioscience\n2.4,"San Diego, CA","San Diego, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$50 to $100 million (USD),-1
940,940,Revenue Analytics Manager,$45K-$78K (Glassdoor est.),HOVER uses patented technology making it possi...,4.8,HOVER\n4.8,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1
941,941,Sr. Scientist Method Development,$50K-$110K (Glassdoor est.),Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Marietta, GA","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
942,942,"Associate Scientist, LC/MS Biologics",$44K-$96K (Glassdoor est.),Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Ithaca, NY","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1
943,943,"Research Scientist, Immunology - Cancer Biology",Employer Provided Salary:$100K-$140K,"Research Scientist, Immunology - Cancer Biolog...",-1.0,Kronos Bio,"Cambridge, MA","San Mateo, CA",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1
944,944,IT - Data Engineer II,$61K-$119K (Glassdoor est.),IT - Data Engineer II\n\nThe Data Engineer II ...,3.4,Arbella Insurance\n3.4,"Quincy, MA","Quincy, MA",1001 to 5000 employees,1988,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1
945,945,Machine Learning Engineer (NLP),$80K-$142K (Glassdoor est.),CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation\n4.1,"Palo Alto, CA","Palo Alto, CA",1 to 50 employees,2007,Company - Private,K-12 Education,Education,Unknown / Non-Applicable,-1
946,946,Senior Data Analyst,$99K-$178K (Glassdoor est.),Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360\n3.9,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
947,947,Data Science Project Manager,$37K-$100K (Glassdoor est.),"At MassMutual, we are passionate about helping...",3.6,MassMutual\n3.6,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1
948,948,Data Engineer,$62K-$113K (Glassdoor est.),Do you find data architecture exciting? Does b...,3.9,Fivestars\n3.9,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn"
949,949,"Principal, Data Science - Advanced Analytics",$86K-$137K (Glassdoor est.),IQVIA is the leading human data science compan...,3.6,IQVIA\n3.6,"Plymouth Meeting, PA","Durham, NC",10000+ employees,2017,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences"
950,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck"
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini"
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1
954,954,Data Engineer,-1,Loading...\n\nTitle: Data Engineer\n\nLocation...,4.8,IGNW\n4.8,"Austin, TX","Portland, OR",201 to 500 employees,2015,Company - Private,IT Services,Information Technology,$25 to $50 million (USD),Slalom
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1

In [27]:
df.isnull().sum()

Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

# salary parsing

In [71]:
df['hourly'] = df['Salary Estimate'].apply(lambda x: 1 if 'per hour' in x.lower() else 0)

In [72]:
df['employer_provided'] = df['Salary Estimate'].apply(lambda x: 1 if 'employer provided salary:' in x.lower() else 0)

In [82]:
df

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5
5,5,Data Scientist,$71K-$119K (Glassdoor est.),CyrusOne is seeking a talented Data Scientist ...,3.4,CyrusOne\n3.4,"Dallas, TX","Dallas, TX",201 to 500 employees,2000,Company - Public,Real Estate,Real Estate,$1 to $2 billion (USD),"Digital Realty, CoreSite, Equinix",0,0,71,119,95.0
6,6,Data Scientist,$54K-$93K (Glassdoor est.),Job Description\n\n**Please only local candida...,4.1,ClearOne Advantage\n4.1,"Baltimore, MD","Baltimore, MD",501 to 1000 employees,2008,Company - Private,Banks & Credit Unions,Finance,Unknown / Non-Applicable,-1,0,0,54,93,73.5
7,7,Data Scientist,$86K-$142K (Glassdoor est.),Advanced Analytics – Lead Data Scientist\nOver...,3.8,Logic20/20\n3.8,"San Jose, CA","Seattle, WA",201 to 500 employees,2005,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,86,142,114.0
8,8,Research Scientist,$38K-$84K (Glassdoor est.),SUMMARY\n\nThe Research Scientist I will be ta...,3.3,Rochester Regional Health\n3.3,"Rochester, NY","Rochester, NY",10000+ employees,2014,Hospital,Health Care Services & Hospitals,Health Care,$500 million to $1 billion (USD),-1,0,0,38,84,61.0
9,9,Data Scientist,$120K-$160K (Glassdoor est.),isn’t your usual company. Our work is powered ...,4.6,<intent>\n4.6,"New York, NY","New York, NY",51 to 200 employees,2009,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Clicktripz, SmarterTravel",0,0,120,160,140.0
10,10,Data Scientist,$126K-$201K (Glassdoor est.),"At Wish, our Data Science & Engineering team i...",3.5,Wish\n3.5,"San Jose, CA","San Francisco, CA",501 to 1000 employees,2011,Company - Private,Other Retail Stores,Retail,$1 to $2 billion (USD),-1,0,0,126,201,163.5
11,11,Data Scientist,$64K-$106K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nSumma...",4.1,ManTech\n4.1,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,0,0,64,106,85.0
12,12,Staff Data Scientist - Technology,$106K-$172K (Glassdoor est.),Position Summary...\nDrives the execution of m...,3.2,Walmart\n3.2,"Plano, TX","Bentonville, AR",10000+ employees,1962,Company - Public,"Department, Clothing, & Shoe Stores",Retail,$10+ billion (USD),"Target, Costco Wholesale, Amazon",0,0,106,172,139.0
13,13,Data Analyst,$46K-$85K (Glassdoor est.),"Are you an experienced Data Analyst, skilled a...",4.1,Yesler\n4.1,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,-1,0,0,46,85,65.5
14,14,Data Scientist,$83K-$144K (Glassdoor est.),Job Description\n\n\nTakeda is looking for a D...,3.7,Takeda Pharmaceuticals\n3.7,"Cambridge, MA","OSAKA, Japan",10000+ employees,1781,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Novartis, Baxter, Pfizer",0,0,83,144,113.5
15,15,Data Engineer I,$102K-$190K (Glassdoor est.),This opportunity is within Audibles Data Engin...,3.6,Audible\n3.6,"Newark, NJ","Newark, NJ",1001 to 5000 employees,1995,Subsidiary or Business Segment,Motion Picture Production & Distribution,Media,Unknown / Non-Applicable,-1,0,0,102,190,146.0
16,16,"Scientist I/II, Biology",$67K-$137K (Glassdoor est.),"Scientist I/II, Biology\n\nCambridge, MA\n\nBI...",3.9,Blueprint Medicines\n3.9,"Cambridge, MA","Cambridge, MA",51 to 200 employees,2011,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $5 million (USD),"bluebird bio, Agios Pharmaceuticals, Celgene",0,0,67,137,102.0
17,17,Customer Data Scientist,$118K-$189K (Glassdoor est.),Company Overview\n\nH2O.ai is the open source ...,4.3,h2o.ai\n4.3,"Mountain View, CA","Mountain View, CA",201 to 500 employees,2011,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,118,189,153.5
18,18,Data Scientist - Health Data Analytics,$110K-$175K (Glassdoor est.),"At Nuna, our mission is to make high-quality h...",4.2,Nuna\n4.2,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2010,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1,0,0,110,175,142.5
19,19,Data Scientist,$64K-$111K (Glassdoor est.),"Pinnacol Assurance does just one thing, and do...",4.0,Pinnacol Assurance\n4.0,"Denver, CO","Denver, CO",501 to 1000 employees,1915,Nonprofit Organization,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,64,111,87.5
20,20,Data Scientist,$81K-$130K (Glassdoor est.),About Our Team\n\nWe understand that the first...,3.2,Porch\n3.2,"Seattle, WA","Seattle, WA",201 to 500 employees,2012,Company - Private,Internet,Information Technology,Unknown / Non-Applicable,"Angie's List, HomeAdvisor, Thumbtack",0,0,81,130,105.5
21,21,Senior Data Scientist / Machine Learning,$73K-$119K (Glassdoor est.),IMMEDIATE NEED FOR A SENIOR DATA SCIENTIST / M...,3.9,Health IQ\n3.9,"Dallas, TX","Mountain View, CA",201 to 500 employees,2013,Company - Private,Insurance Agencies & Brokerages,Insurance,Unknown / Non-Applicable,-1,0,0,73,119,96.0
22,22,Data Scientist - Quantitative,$86K-$139K (Glassdoor est.),Truckstop.com is hiring a Data Scientist for o...,3.8,Truckstop.com\n3.8,"Chicago, IL","New Plymouth, ID",501 to 1000 employees,1995,Company - Private,Logistics & Supply Chain,Transportation & Logistics,Unknown / Non-Applicable,-1,0,0,86,139,112.5
23,23,Data Scientist,$63K-$105K (Glassdoor est.),Position Summary\nOur Data Science team is cur...,4.3,SMC 3\n4.3,"Louisville, KY","Peachtree City, GA",51 to 200 employees,1935,Nonprofit Organization,Logistics & Supply Chain,Transportation & Logistics,$10 to $25 million (USD),-1,0,0,63,105,84.0
25,25,Data Scientist,$109K-$177K (Glassdoor est.),Are you passionate about solving challenging p...,4.0,Novetta\n4.0,"Herndon, VA","Mc Lean, VA",501 to 1000 employees,2012,Company - Private,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"Leidos, CACI International, Booz Allen Hamilton",0,0,109,177,143.0
26,26,Digital Health Data Scientist,$63K-$110K (Glassdoor est.),ROLE SUMMARY\n\nThe Digital Health Data Scient...,4.0,Pfizer\n4.0,"Cambridge, MA","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,110,86.5
27,27,Data Scientist,$75K-$124K (Glassdoor est.),As the Enterprise Data and Analytics Center of...,3.5,First Tech Federal Credit Union\n3.5,"Hillsboro, OR","San Jose, CA",1001 to 5000 employees,1952,Company - Private,Banks & Credit Unions,Finance,$100 to $500 million (USD),-1,0,0,75,124,99.5
28,28,Associate Data Analyst,$34K-$61K (Glassdoor est.),"Friday, January 17, 2020\n\nOur Enterprise Dat...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0,34,61,47.5
29,29,Clinical Data Scientist,$63K-$105K (Glassdoor est.),THIS ROLE MUST BE BASED IN SAN DIEGO\n\nAs par...,4.0,Pfizer\n4.0,"Groton, CT","New York, NY",10000+ employees,1849,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1,0,0,63,105,84.0
30,30,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
920,920,"Scientist, Molecular/Cellular Biologist",$49K-$97K (Glassdoor est.),"[1]Scientist, Molecular/Cellular Biologist\n\n...",2.9,Audentes Therapeutics\n2.9,"South San Francisco, CA","San Francisco, CA",201 to 500 employees,2012,Subsidiary or Business Segment,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"BioMarin Pharmaceutical, Sangamo Therapeutics,...",0,0,49,97,73.0
921,921,Staff Scientist-Downstream Process Development,$49K-$113K (Glassdoor est.),ABL is seeking a Staff Scientist for the Downs...,2.7,Advanced BioScience Laboratories\n2.7,"Rockville, MD","Rockville, MD",201 to 500 employees,1961,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$25 to $50 million (USD),-1,0,0,49,113,81.0
924,924,Data Scientist,$96K-$161K (Glassdoor est.),SummaryProvide data management and statistical...,3.2,"Numeric, LLC\n3.2","Philadelphia, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0,96,161,128.5
926,926,Scientist - Analytical Services,$65K-$134K (Glassdoor est.),British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0,0,65,134,99.5
928,928,"Associate Scientist / Sr. Associate Scientist,...",$59K-$125K (Glassdoor est.),"Who we are\n\n23andMe, the leading consumer ge...",4.0,23andMe\n4.0,"South San Francisco, CA","Sunnyvale, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,"Ancestry, Verily Life Sciences, Abbott Laborat...",0,0,59,125,92.0
929,929,Associate Data Analyst- Graduate Development P...,$32K-$59K (Glassdoor est.),Overview\n\n\nNational Interstate is a member ...,3.3,National Interstate\n3.3,"Richfield, OH","Richfield, OH",501 to 1000 employees,1989,Company - Private,Insurance Carriers,Insurance,$500 million to $1 billion (USD),-1,0,0,32,59,45.5
930,930,Sr. Data Engineer,$87K-$158K (Glassdoor est.),Join our team of Data Consultants and work on ...,4.5,Moser Consulting\n4.5,"Indianapolis, IN","Indianapolis, IN",51 to 200 employees,1996,Company - Private,Consulting,Business Services,$25 to $50 million (USD),-1,0,0,87,158,122.5
931,931,Clinical Data Analyst,$27K-$48K (Glassdoor est.),Job Summary\n\n\nGreenway Health is actively s...,3.0,Greenway Health\n3.0,"Tampa, FL","Tampa, FL",1001 to 5000 employees,1977,Subsidiary or Business Segment,Enterprise Software & Network Solutions,Information Technology,$100 to $500 million (USD),"eClinicalWorks, NextGen Healthcare, athenahealth",0,0,27,48,37.5
932,932,IT Associate Data Analyst,$39K-$69K (Glassdoor est.),"Monday, November 25, 2019\n\nOur Personal Line...",3.7,The Hanover Insurance Group\n3.7,"Worcester, MA","Worcester, MA",5001 to 10000 employees,1852,Company - Public,Insurance Carriers,Insurance,$5 to $10 billion (USD),-1,0,0,39,69,54.0
933,933,Business Data Analyst,$36K-$71K (Glassdoor est.),(We are unable to sponsor for this role now or...,3.8,Fareportal\n3.8,"New York, NY","New York, NY",1001 to 5000 employees,2002,Company - Private,Travel Agencies,Travel & Tourism,$2 to $5 billion (USD),"Expedia Group, Orbitz Worldwide, Priceline.com",0,0,36,71,53.5
934,934,Senior Insurance Data Scientist,$107K-$173K (Glassdoor est.),"What We'll Bring:\n\nAt TransUnion, we have a ...",3.9,TransUnion\n3.9,"Chicago, IL","Chicago, IL",5001 to 10000 employees,1968,Company - Public,Financial Analytics & Research,Finance,$1 to $2 billion (USD),-1,0,0,107,173,140.0
935,935,Senior Data Science Systems Engineer,$56K-$99K (Glassdoor est.),"MITRE’s Army Concepts, Platforms and Theater O...",3.2,MITRE\n3.2,"Hampton, VA","Bedford, MA",5001 to 10000 employees,1958,Nonprofit Organization,Federal Agencies,Government,$1 to $2 billion (USD),"Battelle, General Atomics, SAIC",0,0,56,99,77.5
936,936,ENVIRONMENTAL ENGINEER/SCIENTIST,Employer Provided Salary:$25-$28 Per Hour,"McPhail Associates, LLC is a geotechnical and ...",3.3,Mcphail Associates\n3.3,"Cambridge, MA","Cambridge, MA",1 to 50 employees,1976,Company - Private,Construction,"Construction, Repair & Maintenance",Unknown / Non-Applicable,-1,1,1,25,28,26.5
938,938,Senior Scientist - Regulatory Submissions,$80K-$155K (Glassdoor est.),British American Tobacco\nReynolds American In...,3.1,Reynolds American\n3.1,"Winston-Salem, NC","Winston-Salem, NC",5001 to 10000 employees,1875,Company - Private,Consumer Products Manufacturing,Manufacturing,$10+ billion (USD),-1,0,0,80,155,117.5
939,939,Scientist - Biomarker and Flow Cytometry,$43K-$98K (Glassdoor est.),"Crown Bioscience, a JSR Life Sciences company,...",2.4,Crown Bioscience\n2.4,"San Diego, CA","San Diego, CA",501 to 1000 employees,2006,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$50 to $100 million (USD),-1,0,0,43,98,70.5
940,940,Revenue Analytics Manager,$45K-$78K (Glassdoor est.),HOVER uses patented technology making it possi...,4.8,HOVER\n4.8,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2011,Company - Private,Computer Hardware & Software,Information Technology,$25 to $50 million (USD),-1,0,0,45,78,61.5
941,941,Sr. Scientist Method Development,$50K-$110K (Glassdoor est.),Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Marietta, GA","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0,50,110,80.0
942,942,"Associate Scientist, LC/MS Biologics",$44K-$96K (Glassdoor est.),Q2 Solutions is a leading clinical trial labor...,2.9,Q2 Solutions\n2.9,"Ithaca, NY","Morrisville, NC",1001 to 5000 employees,2015,Company - Private,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,Unknown / Non-Applicable,-1,0,0,44,96,70.0
943,943,"Research Scientist, Immunology - Cancer Biology",Employer Provided Salary:$100K-$140K,"Research Scientist, Immunology - Cancer Biolog...",-1.0,Kronos Bio,"Cambridge, MA","San Mateo, CA",Unknown,-1,Company - Private,-1,-1,Unknown / Non-Applicable,-1,0,1,100,140,120.0
944,944,IT - Data Engineer II,$61K-$119K (Glassdoor est.),IT - Data Engineer II\n\nThe Data Engineer II ...,3.4,Arbella Insurance\n3.4,"Quincy, MA","Quincy, MA",1001 to 5000 employees,1988,Company - Private,Insurance Carriers,Insurance,$100 to $500 million (USD),-1,0,0,61,119,90.0
945,945,Machine Learning Engineer (NLP),$80K-$142K (Glassdoor est.),CK-12’s mission is to provide free access to o...,4.1,CK-12 Foundation\n4.1,"Palo Alto, CA","Palo Alto, CA",1 to 50 employees,2007,Company - Private,K-12 Education,Education,Unknown / Non-Applicable,-1,0,0,80,142,111.0
946,946,Senior Data Analyst,$99K-$178K (Glassdoor est.),Senior Data Analyst\n\nAbout us\n\n\nLife360 b...,3.9,Life360\n3.9,"San Francisco, CA","San Francisco, CA",51 to 200 employees,2008,Company - Public,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1,0,0,99,178,138.5
947,947,Data Science Project Manager,$37K-$100K (Glassdoor est.),"At MassMutual, we are passionate about helping...",3.6,MassMutual\n3.6,"Boston, MA","Springfield, MA",5001 to 10000 employees,1851,Company - Private,Insurance Carriers,Insurance,$10+ billion (USD),-1,0,0,37,100,68.5
948,948,Data Engineer,$62K-$113K (Glassdoor est.),Do you find data architecture exciting? Does b...,3.9,Fivestars\n3.9,"San Francisco, CA","San Francisco, CA",201 to 500 employees,2011,Company - Private,Internet,Information Technology,$100 to $500 million (USD),"Belly, SpotOn",0,0,62,113,87.5
949,949,"Principal, Data Science - Advanced Analytics",$86K-$137K (Glassdoor est.),IQVIA is the leading human data science compan...,3.6,IQVIA\n3.6,"Plymouth Meeting, PA","Durham, NC",10000+ employees,2017,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$2 to $5 billion (USD),"PPD, INC Research, PRA Health Sciences",0,0,86,137,111.5
950,950,"Sr Scientist, Immuno-Oncology - Oncology",$58K-$111K (Glassdoor est.),Site Name: USA - Massachusetts - Cambridge\nPo...,3.9,GSK\n3.9,"Cambridge, MA","Brentford, United Kingdom",10000+ employees,1830,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),"Pfizer, AstraZeneca, Merck",0,0,58,111,84.5
951,951,Senior Data Engineer,$72K-$133K (Glassdoor est.),THE CHALLENGE\nEventbrite has a world-class da...,4.4,Eventbrite\n4.4,"Nashville, TN","San Francisco, CA",1001 to 5000 employees,2006,Company - Public,Internet,Information Technology,$100 to $500 million (USD),"See Tickets, TicketWeb, Vendini",0,0,72,133,102.5
952,952,"Project Scientist - Auton Lab, Robotics Institute",$56K-$91K (Glassdoor est.),The Auton Lab at Carnegie Mellon University is...,2.6,Software Engineering Institute\n2.6,"Pittsburgh, PA","Pittsburgh, PA",501 to 1000 employees,1984,College / University,Colleges & Universities,Education,Unknown / Non-Applicable,-1,0,0,56,91,73.5
953,953,Data Science Manager,$95K-$160K (Glassdoor est.),Data Science ManagerResponsibilities:\n\nOvers...,3.2,"Numeric, LLC\n3.2","Allentown, PA","Chadds Ford, PA",1 to 50 employees,-1,Company - Private,Staffing & Outsourcing,Business Services,$5 to $10 million (USD),-1,0,0,95,160,127.5
955,955,Research Scientist – Security and Privacy,$61K-$126K (Glassdoor est.),Returning Candidate? Log back in to the Career...,3.6,Riverside Research Institute\n3.6,"Beavercreek, OH","Arlington, VA",501 to 1000 employees,1967,Nonprofit Organization,Federal Agencies,Government,$50 to $100 million (USD),-1,0,0,61,126,93.5

In [74]:
#checking salary estimate shounld't equalto -1
df=df[df['Salary Estimate'] != '-1']

df.count()

Unnamed: 0           742
Job Title            742
Salary Estimate      742
Job Description      742
Rating               742
Company Name         742
Location             742
Headquarters         742
Size                 742
Founded              742
Type of ownership    742
Industry             742
Sector               742
Revenue              742
Competitors          742
hourly               742
employer_provided    742
dtype: int64

In [75]:
#removing (Glassdoor est.)from salary estimate column, through lambda fuction splitting data from '(' and taking only first list[0]
salary = df['Salary Estimate'].apply(lambda x: x.split('(')[0])

In [76]:
#removing k and $ sign
minus_Kd = salary.apply(lambda x: x.replace('K','').replace('$',''))

In [77]:
min_hr = minus_Kd.apply(lambda x: x.lower().replace('per hour','').replace('employer provided salary:',''))

In [79]:
df['min_salary'] = min_hr.apply(lambda x: int(x.split('-')[0]))
df['max_salary'] = min_hr.apply(lambda x: int(x.split('-')[1]))
df['avg_salary'] = (df.min_salary+df.max_salary)/2

In [81]:
df.head(5)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,0,0,53,91,72.0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,0,0,63,112,87.5
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,0,0,80,90,85.0
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5

# Company name text only

In [83]:
df['company_txt'] = df.apply(lambda x: x['Company Name'] if x['Rating'] <0 else x['Company Name'][:-3], axis = 1)

# state field

In [85]:
df['job_state'] = df['Location'].apply(lambda x: x.split(',')[1])

In [86]:
df.job_state.value_counts()

 CA             151
 MA             103
 NY              72
 VA              41
 IL              40
 MD              35
 PA              33
 TX              28
 NC              21
 WA              21
 NJ              17
 FL              16
 OH              14
 TN              13
 CO              11
 DC              11
 UT              10
 WI              10
 IN              10
 MO               9
 AZ               9
 AL               8
 MI               6
 KY               6
 GA               6
 DE               6
 CT               5
 IA               5
 NE               4
 OR               4
 LA               4
 KS               3
 NM               3
 ID               2
 MN               2
 Los Angeles      1
 RI               1
 SC               1
Name: job_state, dtype: int64

In [87]:
df['same_state'] = df.apply(lambda x: 1 if x.Location == x.Headquarters else 0, axis = 1)

In [88]:
df.head(5)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,...,Revenue,Competitors,hourly,employer_provided,min_salary,max_salary,avg_salary,company_txt,job_state,same_state
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,...,$50 to $100 million (USD),-1,0,0,53,91,72.0,Tecolote Research\n,NM,0
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,...,$2 to $5 billion (USD),-1,0,0,63,112,87.5,University of Maryland Medical System\n,MD,0
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,...,$100 to $500 million (USD),-1,0,0,80,90,85.0,KnowBe4\n,FL,1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,...,$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",0,0,56,97,76.5,PNNL\n,WA,1
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,...,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",0,0,86,143,114.5,Affinity Solutions\n,NY,1

# age of company

In [89]:
df['age'] = df.Founded.apply(lambda x: x if x <1 else 2020 - x)

# #parsing of job description (python, etc.)

In [94]:
df['python_yn'] = df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)

In [104]:
df.python_yn.value_counts()

1    392
0    350
Name: python_yn, dtype: int64

In [103]:
#r_studio
df['R_yn'] = df['Job Description'].apply(lambda x: 1 if 'r studio' in x.lower() or 'r-studio' in x.lower() else 0)
df.R_yn.value_counts()

0    740
1      2
Name: R_yn, dtype: int64

In [105]:
df['spark'] = df['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)
df.spark.value_counts()

0    575
1    167
Name: spark, dtype: int64

In [106]:
#aws 
df['aws'] = df['Job Description'].apply(lambda x: 1 if 'aws' in x.lower() else 0)
df.aws.value_counts()

0    566
1    176
Name: aws, dtype: int64

In [107]:
#excel
df['excel'] = df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)
df.excel.value_counts()

1    388
0    354
Name: excel, dtype: int64

In [108]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors',
       'hourly', 'employer_provided', 'min_salary', 'max_salary', 'avg_salary',
       'company_txt', 'job_state', 'same_state', 'age', 'python_yn', 'R_yn',
       'spark', 'aws', 'excel'],
      dtype='object')

In [109]:
df_out = df.drop(['Unnamed: 0'], axis =1)

In [110]:
df_out.to_csv('salary_data_cleaned.csv',index = False)